version: "3.3"
services:
  nginx:
    image: nginx:1.15.4-alpine
    volumes:
      - /Users/jiyang/Documents/train/todo-frontend/build:/app
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - "gateway-service"
    deploy:
      restart_policy:
        condition: on-failure
    
  mysql:
    image: mysql:5.7
    # volumes:
    #   - /Users/jiyang/Documents/train/mysql-todo:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: "password"
       TZ: Asia/Shanghai
    ports:
      - "3307:3306"
    restart: always
    
  user-service:
    image: yangjier/todo-user-service
    restart: always
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    ports:
      - "8082:8082"
    depends_on:
      - "config-service"
      - "mysql"

  todo-service:
    image: yangjier/todo-todo-service
    restart: always
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - "8088:8088"
    depends_on:
      - "config-service"
      - "mysql"
  
  gateway-service:
    image: yangjier/todo-gateway-service
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - "config-service"
    deploy:
      restart_policy:
        condition: on-failure

  config-service:
    image: yangjier/todo-config-service
    restart: on-failure
    ports:
      - "8888:8888"
    deploy:
      restart_policy:
        condition: on-failure 